
# Use a base image with OpenJDK 11 JRE
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Spring Boot JAR file into the container
# Replace 'your-application.jar' with the actual name of your built JAR file
COPY target/ikjot-practice-1.0.0 ikjot-practice.jar

# Expose the port your Spring Boot application listens on (default is 8080)
EXPOSE 8080

# Define the command to run your Spring Boot application
ENTRYPOINT ["java", "-jar", "ikjot-practice.jar"]
